# Generated by Django 5.0.6 on 2024-06-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_employee_id_remove_employee_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='idd',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
