# Generated by Django 5.0.6 on 2024-06-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_employee_idd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='idd',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
