# Generated by Django 5.0.6 on 2024-06-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_employee_idd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='attendance',
            new_name='approved',
        ),
    ]
