# Generated by Django 5.0.6 on 2024-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_employee_is_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_manager',
        ),
    ]
