# Generated by Django 5.0.6 on 2024-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_manager_id_manager_idd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.IntegerField(default=0),
        ),
    ]
