# Generated by Django 5.0.6 on 2024-06-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_delete_manager_employee_is_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
