# Generated by Django 5.0.6 on 2024-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='idd',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
