# Generated by Django 5.0.6 on 2024-06-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='registered_face',
            field=models.IntegerField(default=0),
        ),
    ]
