# Generated by Django 5.0.6 on 2024-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_employee_registered_face'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='registered_face',
        ),
        migrations.AddField(
            model_name='employee',
            name='face_update',
            field=models.IntegerField(default=0),
        ),
    ]
