# Generated by Django 5.0.6 on 2024-06-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_employee_registered_face_employee_face_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='face_update',
        ),
        migrations.AddField(
            model_name='employee',
            name='update_face',
            field=models.IntegerField(default=0),
        ),
    ]
