# Generated by Django 5.0.6 on 2024-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_employee_face_update_employee_update_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='update_face',
            field=models.IntegerField(default=99),
        ),
    ]
