# Generated by Django 5.0.6 on 2024-06-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_employee_update_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='update_face_req',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update_face',
            field=models.IntegerField(default=0),
        ),
    ]
