# Generated by Django 5.0.6 on 2024-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Req_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='Req_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
