# Generated by Django 5.0.6 on 2024-06-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_location_req_lat_location_req_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='Req_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='Req_long',
        ),
        migrations.AddField(
            model_name='location',
            name='access',
            field=models.IntegerField(default=0),
        ),
    ]
