# Generated by Django 5.0.6 on 2024-06-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_location_req_lat_remove_location_req_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
