# Generated by Django 5.0.6 on 2024-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_location_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='loc_name',
            field=models.CharField(default='No-Name', max_length=50),
        ),
    ]
