# Generated by Django 5.0.6 on 2024-07-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_location_loc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='employee_images/'),
        ),
    ]
